# Generated by Django 4.2.3 on 2023-07-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsors',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsors',
            name='pic',
            field=models.ImageField(default='chanels_pics/default.png', upload_to='chanels_pics/'),
        ),
    ]
