# Generated by Django 4.2.3 on 2023-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0002_rename_url_sponsors_link_sponsors_name_sponsors_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
