# Generated by Django 4.2.3 on 2023-07-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='left_chanels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
