# Generated by Django 4.2.3 on 2023-07-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsors',
        ),
    ]
