# Generated by Django 4.2.3 on 2023-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control', '0002_delete_sponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('error', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
